spring.application.name=backend
#локально 
spring.datasource.url=jdbc:postgresql://localhost:5432/barsikdb

spring.datasource.username=postgres_user
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
jwt.expiration-time=86400000

springdoc.swagger-ui.path=/swagger-ui.html